### ISSUE TITLE
[BUG] going to the step page from the workflow diagram page shows no config items

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#205]
see the attached screenshot - this step has 20 config items normally - they are visible when the step form is opened from the hierarchy view or the code lens

![Screen Shot 2019-12-17 at 4 06 32 PM](https://user-images.githubusercontent.com/13432105/71007493-61e2a900-20e7-11ea-9c21-f559020149b9.png)

**Comment by Foxhoundn** [comment]
This is because of a bug on backend.

When requesting data with `return-interface-data` backend returns classes in format `[classname]` instead of `[{ name: classname }]`.

This results in frontend sending the event `get-config-items` with `{"classes":["QorusNormalStep2"],"iface_kind":"step"}` instead of `get-config-items {"classes":[{name: "QorusNormalStep2"}],"iface_kind":"step"}`

When opening from code lens, backend sends correct data, hence why it only breaks when using the `return-interface-data` event, but not `return-initial-data`.

**Comment by martin-zemek** [comment]
Backend part fixed, classes in `return-interface-data` are now in the required format.

But this issue is not fixed yet, config items are still not there if a step is opened from a step diagram.
The reason is that frontend in its `get-config-items` message does not send `iface_id`.

**Comment by Foxhoundn** [comment]
@martin-zemek the iface_id is not send to the frontend when requesting the step data, that's why it's not there.

**Comment by martin-zemek** [comment]
fixed
