### ISSUE TITLE
vscode_java.exports.getDocumentSymbols() does not find symbols

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#236]
In the repo `demos` there are 8 java files and for 5 of them (those in the subdir `gsi/IT-MIP-70-JAVA`) `getDocumentSymbols()` does not find any symbols. (I mean: any symbols at all, not symbols satisfying some additional conditions.)

**Comment by martin-zemek** [comment]
actually, it does not find any symbols even in a most simple file like this:
```
class C {
}
```

**Comment by omusil24** [comment]
That's probably because the Java extensions didn't initialize yet. Try using `getJavaDocumentSymbolsWithWait()`.

**Comment by martin-zemek** [comment]
no, because it's called for all files - in the function processJavaDocumentSymbols() - and for three files (those in the subdir `salesforce.com/java`) some symbols are returned

**Comment by omusil24** [comment]
Not a bug. The problem is that the file names are not valid Java identifiers, and also the file names do not correspond with the names of the classes in the files.

The files should be renamed as follows:
`Mip70ItLockR11-v1.0.qstep.java` -> `Mip70ItLockR11.java`
`Mip70ItImportR11-v1.0.qstep.java` -> `Mip70ItImportR11.java`
`R11Lib-v1.0.qclass.java` -> `R11Lib.java`
`SeplLib-v1.0.qclass.java` -> `SeplLib.java`
`Mip70ItFinalizeR11-v1.0.qstep.java` -> `Mip70ItFinalizeR11.java`

Then everything will work.

**Comment by martin-zemek** [comment]
change generating the code, so that it conforms to java

**Comment by martin-zemek** [comment]
fixed
