### ISSUE TITLE
[BUG] when adding any new object to an existing object, automatically set the directory of the parent object

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#339]

**Comment by martin-zemek** [comment]
If we create a new workflow from where we create new steps steps then only the front-end can handle it since the back-end knows nothing about the workflow yet.

If we edit an existing workflow (or if the workflow has already been saved during the creation process) then the backend can deal with it as well.

**Comment by davidnich** [comment]
@martin-zemek this is no longer working for me

**Comment by Foxhoundn** [comment]
Fixed
