### ISSUE TITLE
[BUG] inherited config items not being saved

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#387]

**Comment by martin-zemek** [comment]
It's a frontend bug.
Among the many messages `get-config-items` that are sent when moving around between Next and Back and Config items, some have the argument `classes: []` and some have in the `classes` parameter the expected class names. The value `classes: []` makes the backend forget about the inherited config items.
1. If the interface happens to be saved after last call with `classes:[]`, no config items are saved
2. If the interface happens to be saved after last call with correct value of `classes`, config items are saved but without the value (in case some has been set) because the backend prepared the inherited config items anew.

This makes the backend also to forget the config items of inherited classes. If the interface is savedNext message `get-config-items` contains the classes again, which makes the backend to find the inherited config items again but of course values is not there
