### ISSUE TITLE
[FEATURE] Show notifications when workflow is saved after editing

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#393]
Notification is shown when workflow is created, but not when it's updated.

**Comment by martin-zemek** [comment]
It's true for any kind of interface, not only for workflow.

My original idea was to give notification that new files have been created or that some files have been removed (on changing the target path), not to give notification that the creation was successful. That's why notification is not always shown after any successful edit.

And, as soon as we have the info page it will open after edit.

**Comment by turlyalz** [comment]
Well, opening the info page is good. I'm wondering how users will know that their changes have been successfully apllied?
