### ISSUE TITLE
[BUG] cannot edit Java interfaces from the interface tree

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#543]
clicking on `Submit` for any Java step results in a timeout

**Comment by Foxhoundn** [comment]
`rejected promise not handled within 1 second: TypeError: Cannot read property 'length' of undefined
extensionHostProcess.js:920
stack trace: TypeError: Cannot read property 'length' of undefined
	at ClassCreator.renameClassAndBaseClass (/Users/filipwitosz/Code/Projects/qorus-vscode/out/qorus_creator/InterfaceCreator.js:458:48)
	at ClassCreator.editImpl (/Users/filipwitosz/Code/Projects/qorus-vscode/out/qorus_creator/ClassCreator.js:130:43)
	at /Users/filipwitosz/Code/Projects/qorus-vscode/out/qorus_creator/InterfaceCreator.js:390:22`

**Comment by martin-zemek** [comment]
Actually, no java interface can be edited unless it's opened from the code lenses since the symbol parser returns nothing.

I've fixed the resulting crash, so now there's is an error message instead.

You may think that it works now, for example if you only change the description or something that is not in the code file. But no change is ever done to the code file so if you change the class name it will be changed only in the yaml file.

**Comment by martin-zemek** [comment]
fixed with #573
