### ISSUE TITLE
[BUG] regenerating service source fails with an empty source file or a missing method

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#582]
in this case the front end times out - I assume there is a backend error.

If I re-add an empty method declaration for the missing method(s) (only tested with 1 method - init()) - then method source code generation succeeds.

**Comment by martin-zemek** [comment]
I don't understand the description - what steps are you doing?

**Comment by davidnich** [comment]
@martin-zemek in fact I was changing a service from Qore -> Java and vice versa.  To do this I edited the yaml and changed both the language and the file name.  Then I generated an empty file and tried to regenerate the service source from the metadata.  For Java I was able to make it work (although I think there is an issue there - I will get back to testing that later), but for Qore, the IDE freezes unless at least the Qore class exists with declared methods defined.

For example, if I create a new Qore service source file like this:
```
class MyService inherits QorusService {
}
```

And there is an `init()` method declared, when trying to regenerate the service source code, the IDE will time out.  After I add in an empty `init()` method declaration, it works as expected again.

Let me know if you need more info.

**Comment by martin-zemek** [comment]
Are you not getting any messages (yaml and source file mismatch)?
Empty file is an incorrect source file (in exactly the same sense as if there was any other kind of nonsense in the file) so it cannot positively work.

We could think of implementing the following behaviour: if there is yaml/source mismatch or if parsing the source file fails then ask the user to choose either to cancel the "edit" action or continue treating the action as a "create new" action (prefill the edit form with the yaml data and overwrite the source file).

**Comment by davidnich** [comment]
@martin-zemek I don't recall getting such a message, but it's possible.  

The cancel / create new approach is a winner IMO - at the moment it's just freezing, and having the IDE regenerate the source on request if a super useful feature - like this we can even support converting language (i.e. the IDE will prompt the user to confirm that they will lose all custom code if they continue)

**Comment by martin-zemek** [comment]
Behaviour proposal:
There will be two reasons for regenerating the source code:
- incorrect code, either parsing failure or mismatch between yaml and source
- language change

The first case is detected by the backend and in this case the backend will send to the frontend, along with the interface data, an information (flag) that the frontend should show a question dialog with the `Recreate` and `Cancel` options.
The backend will also send the message to show since it may be different in different situations.

If the user selects `Cancel` then the form should be cleared because it means that the action will not continue in any way.
If the user select Recreate the frontend will just change the `edit_type` to `create`.

The second case is detected by the frontend, so in this case the frontend will present the dialog by itself.

**Comment by martin-zemek** [comment]
Done
